<!DOCTYPE html>
<?php
	lib_load('html');
	__('language')->append('pages');
?>
<html>
	<head>
		<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
		<meta name="viewport" content="initial-scale=1, maximum-scale=1" />
<?php __('cpage')->meta(); ?>
		<title><?= __('page')->getTitle() ?></title>
		<link href="client/css/reset.css" type="text/css" rel="stylesheet" />
		<link href="client/css/common.css" type="text/css" rel="stylesheet" />
		<link href="client/css/flags.css" type="text/css" rel="stylesheet" />
		<link href="client/css/responsive.css" type="text/css" rel="stylesheet" />
<?php
	if (preg_match('/(MSIE [6-8]{1,2})/', $_SERVER['HTTP_USER_AGENT'])):
?>
		<script src="client/js/jquery-1.12.4.min.js" type="text/javascript"></script>
<?php
	else:
		echo HTMLHelpers::JSScript('client/js/jquery-3.3.1.min.js');
	endif;
?>
		<script src="client/js/common.js" type="text/javascript"></script>
		<script type="text/javascript">
			var SiteUrl = "<?= SiteURL?>";
		</script>
<?= __('pre_res')?>
<?php	__('cpage')->resources();?>
	</head>
	<body>
		<div id="wrapper" style="display: none;">
			<span class="col-1-1">
<?php __('cpage')->header(); ?>
			</span>
<?php
	__('page')->insertSnippet('header_view');
	__('page')->insertSnippet('layouts'.DIRECTORY_SEPARATOR.'layout_two_columns');
	__('page')->insertSnippet('footer');
	__('cpage')->footer();
?>
		</div>
	<script src="client/js/common.inc.js" type="text/javascript"></script>
	<script type="text/javascript">
	$('#wrapper').fadeToggle(300);
<?php __('cpage')->domonload(); ?>
	</script>
	</body>
</html>