<!DOCTYPE html>
<?php
	lib_load('html');
	__('language')->append('pages');
?>
<html>
	<head>
		<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
		<meta name="viewport" content="initial-scale=1, maximum-scale=1" />
<?php __('cpage')->meta(); ?>
		<title><?= __('page')->getTitle() ?></title>
<?php
	echo HTMLHelpers::CSSLink("client/css/reset.css");
	echo HTMLHelpers::CSSLink("client/css/common.css");
	echo HTMLHelpers::CSSLink("client/css/flags.css");
	echo HTMLHelpers::CSSLink("client/css/responsive.css");
	if (preg_match('/(MSIE [6-8]{1,2})/', $_SERVER['HTTP_USER_AGENT'])) {
		echo HTMLHelpers::JSScript('client/js/jquery-1.12.4.min.js');
	} else {
		echo HTMLHelpers::JSScript('client/js/jquery-3.1.1.min.js');
	}
?>
		<script src="client/js/common.js" type="text/javascript"></script>
<?php
	echo __('pre_res');
	__('cpage')->resources();
?>
	</head>
	<body>
		<blockquote id="wrapper" class="body-80" style="display: none;">
			<span class="col-1-1">
<?php __('cpage')->header(); ?>
			</span>
<?php
		__('page')->insertSnippet('header_menu');
		__('page')->insertSnippet('layouts' . DIRECTORY_SEPARATOR . 'layout_two_columns');
		__('page')->insertSnippet('footer');
		__('cpage')->footer();
?>
		</blockquote>
	<script src="client/js/common.inc.js" type="text/javascript"></script>
	<script type="text/javascript">
	$('#wrapper').fadeToggle(700);
<?php __('cpage')->domonload(); ?>
	</script>
	</body>
</html>