<!DOCTYPE html>
<?php
lib_load('html');
__('language')->append('pages');
?>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<?php __('cpage')->meta();?>
		<title><?= __('page')->getTitle() ?></title>
		<link rel="stylesheet" href="shared/w3/w3.css" />
		<link rel="stylesheet" href="shared/hrachefront/flags.css" />
		<link rel="stylesheet" href="client/css/common.css" />
		<?= HTMLHelpers::JSScript('shared/jquery/'.((preg_match('/(MSIE [6-8]{1,2})/', $_SERVER['HTTP_USER_AGENT']))? 'jquery-1.12.4.min.js': 'jquery-3.3.1.min.js')) ?>
		<script src="shared/w3/w3.js" type="text/javascript"></script>
		<script src="shared/hrachefront/HracheJS.js" type="text/javascript"></script>
		<script src="client/js/common.js" type="text/javascript"></script>
		<script src="client/js/FrameworkNative.js" type="text/javascript"></script>
		<script type="text/javascript">
		SiteURL = "<?= SiteURL?>";

		$(document).ready(function() {
			<?php require_once(Client.'js'.DIRECTORY_SEPARATOR.'common.inc.js');?>
			<?php __('cpage')->jqueryready(); ?>
		});
		</script>
	<?php __('cpage')->resources();?>
	</head>
	<body id="wrapper">
		<?php __('page')->snippet->insert('header');?>
		<!--	Header	-->

		<?php __('cpage')->content(); ?>
		<!--	Content	-->

		<div class="w3-panel" style="margin-bottom:160px;"></div>
		<?php __('page')->snippet->insert('footer'); ?>
		<!--	Footer -->

		<?php __('cpage')->bottomres(); ?>
		<!--	Bottom resources	-->

		<script type="text/javascript">
		<?php __('cpage')->domonload(); ?>
		</script>
	</body>
</html>
