<h2><?= _abc('additionalinfo') ?></h2>
<span class="col-2-1">
 <input type="text" name="altaddress" id="altaddress" value="<?= post_('altaddress') ?>" placeholder="<?= _abc('altaddress') ?>"/>
 <br/>
 <select name="countryorigin" id="countryorigin">
  <option value=""><?= _abc("countryorigin") ?></option>
  <?= DOMCountries(post_('countryorigin'), '') ?>
 </select>
 <br/>
 <select name="countryassembly" id="countryassembly">
  <option value=""><?= _abc("countryassembly") ?></option>
  <?= DOMCountries(post_('countryassembly'), '') ?>
 </select>
 <br/><input type="text" name="enginesize" value="<?= post_('enginesize') ?>" placeholder="<?= _abc('enginesize') ?>"/>
 <?= ffDesc(new ArrayClass(_abc('engine_')), _abc('measure')) ?>
 <br/>
 <select name='aspirationtype_'>
  <option value=""><?= _abc('aspirationtype') ?></option>
<?php
	foreach (_abc('aspirationtype_') as $key => $val) html_option($val, $key, ($key === post_('aspirationtype_')) ? true : false);
?>
 </select>
 <br/><input type="text" name="acceleration" value="<?= post_('acceleration') ?>" placeholder="<?= _abc('acceleration') ?>"/>
 <br/><input type="text" name="power" value="<?= post_('power') ?>" placeholder="<?= _abc('power') ?>"/>
 <?= ffDesc(new ArrayClass(_abc('power_')), _abc('measure')) ?>
 <br/><input type="text" name="torque" value="<?= post_('torque') ?>" placeholder="<?= _abc('torque') ?>"/>
 <?= ffDesc(new ArrayClass(_abc('torque_')), _abc('measure')) ?>
 <br/><input type="text" name="tirewheelsize" value="<?= post_('tirewheelsize') ?>" placeholder="<?= _abc('tirewheelsize') ?>"/>
<?= ffDesc(new ArrayClass(_abc('tirewheelsize_')), _abc('measure')) ?><br/>
 <select name='drivetype'>
  <option><?= _abc('drivetype') ?></option>
<?php foreach (_abc('drivetype_') as $key => $val) html_option($val, $key);?>
 </select>
 <br/><input type="text" name="seatingscapacity" value="<?= post_('seatingscapacity') ?>" placeholder="<?= _abc('seatingscapacity') ?>"/><br/>
 <select name='doors_'>
  <option value=""><?= _abc('doors') ?></option>
<?php foreach (_abc('doors_') as $key => $val) html_option($val, $key, post_('doors_') ? true : false);?>
 </select>
</span>

<span class="col-2-1">
 <input type="text" name="city_consumption" value="<?= post_('city_consumption') ?>" placeholder="<?= _abc('city_consumption') ?>"/>
 <?= ffDesc(new ArrayClass(_abc('consumption_')), _abc('measure')) ?>
 <br/><input type="text" name="highway_consumption" value="<?= post_('highway_consumption') ?>" placeholder="<?= _abc('highway_consumption') ?>"/>
 <?= ffDesc(new ArrayClass(_abc('consumption_')), _abc('measure')) ?>
 <br/><input type="text" name="combined_consumption" value="<?= post_('combined_consumption') ?>" placeholder="<?= _abc('combined_consumption') ?>"/>
<?= ffDesc(new ArrayClass(_abc('consumption_')), _abc('measure')) ?>
 <br/><input type="text" name="displacement" value="<?= post_('displacement') ?>" placeholder="<?= _abc('displacement') ?>"/>
 <?= ffDesc(new ArrayClass(_abc('displacement_')), _abc('measure')) ?>
 <br/><input type="text" name="co2emissions" value="<?= post_('co2emissions') ?>" placeholder="<?= _abc('co2emissions') ?>"/>
 <br/><input type="text" name="curbweight" value="<?= post_('curbweight') ?>" placeholder="<?= _abc('curbweight') ?>"/>
<?= ffDesc(new ArrayClass(_abc('weight_')), _abc('measure')) ?>
 <br/><input type="text" name="towingcapacity" value="<?= post_('towingcapacity') ?>" placeholder="<?= _abc('towingcapacity') ?>"/>
 <?= ffDesc(new ArrayClass(_abc('capacity_')), _abc('measure')) ?>
 <br/><input type="text" name="cargoallseatsfolded" value="<?= post_('cargoallseatsfolded') ?>" placeholder="<?= _abc('cargoallseatsfolded') ?>"/>
 <br/><input type="text" name="width" value="<?= post_('width') ?>" placeholder="<?= _abc('width') ?>"/>
 <?= ffDesc(new ArrayClass(_abc('dimensions_')), _abc('measure')) ?>
 <br/><input type="text" name="height" value="<?= post_('height') ?>" placeholder="<?= _abc('height') ?>"/>
<?= ffDesc(new ArrayClass(_abc('dimensions_')), _abc('measure')) ?>
 <br/><input type="text" name="length" value="<?= post_('length') ?>" placeholder="<?= _abc('length') ?>" />
<?= ffDesc(new ArrayClass(_abc('dimensions_')), _abc('measure')) ?>
 <br/><input type="text" name="audio_totalnumberofspeakers" value="<?= post_('audio_totalnumberofspeakers') ?>" placeholder="<?= _abc('audio_totalnumberofspeakers') ?>"/>
</span>
