<span class="col-1-1">
 <select name="carbrand" id="carbrand_">
  <option value=""><?= _abc ("brand")?></option>
 <?= DOMOptions_CarBrands (intval (post_ ('carbrand')))?>
 </select>
 <select name="carmodel" id="carmodel_">
  <option value=""><?= _abc ("model")?></option>
 <?= DOMOptions_CarModelsByCarBrand (intval (post_ ('carbrand')), intval (post_ ('carmodel')))?>
 </select>
 <input type="text" name="carmodelman" id="carmodelman" value="<?= post_ ('carmodelman')?>" placeholder="<?= _abc ('carmodelman')?>" /><br/>
 <select name="country" id="country">
  <option value=""><?= _abc("country")?></option>
<?= DOMCountries (post_ ('country'), '')?>
 </select>
 <input type="text" name="state" id="state" placeholder="<?= _abc ('state')?>" />
 <input type="text" name="cityorprovince" id="cityorprovince" placeholder="<?= _abc ('cityorprovince')?>" />
 <input type="text" name="mainaddress" id="mainaddress" placeholder="<?= _abc ('mainaddress')?>" />
</span>

<span class="col-1-1">
 <select name="advtype">
  <option value="free" selected><?= _abc ('freeadv')?></option>
  <option value="spec"><?= _abc ('specadv')?></option>
  <option value="quick"><?= _abc ('quickadv')?></option>
 </select>
 <select name="buyorsell">
  <option value="0" checked /><?= _abc ('isellacar')?></option>
  <option value="1" /><?= _abc ('ibuyacar')?></option>
 </select>
 <select name="vehicletype">
  <option value=""><?= _abc ('vehtype')?></option>
 <?php
  $ar = new ArrayClass (_abc ('vehicletype'));
  $ar->eachItem (function (&$val, $key) {
   printf ('<option value="%s">%s</option>', $key, $val);
  });
 ?>
 </select>
 <select name="measure">
  <option value=""><?= _abc ("measure")?></option>
  <option value="met"><?= _abc ('metric')?></option>
  <option value="imp" ><?= _abc ('imperial')?></option>
 </select>
</span>

<span class="col-1-1">
 <select name="transmissiontype">
  <option value=""><?= _abc ('transmissiontype')?></option>
<?php
$ar = new ArrayClass (_abc ('transmission_types'));
$ar->eachItem (function (&$val, $key) {
 printf ('<option value="%s">%s</option>', $key, $val);
});
?>
 </select>
 <select name="transmissiongears">
  <option value=""><?= _abc ('gears')?></option>
<?php
$ar = new ArrayClass ([4, 5, 6, 'sixandmore']);
$ar->eachItem (function (&$val, $key) {
 printf ('<option value="%s">%s</option>', $key, _abc ($val));
});
?>
 </select>
 <select name='bodytype'>
  <option value=""><?= _abc ('bodytype')?></option>
<?php
$ar = new ArrayClass (_abc ('bodytype_'));
$ar->eachItem (function (&$val, $key) {
 html_option ($val, $key, ($key === post_ ('bodytype')? true : false));
});
?>
 </select>
 <select name='fueltype_'>
  <option value=""><?= _abc ('fueltype')?></option>
<?php
$ar = new ArrayClass (_abc ('fueltype_'));
$ar->eachItem (function (&$val, $key) {
 html_option ($val, $key, ($key === post_ ('fueltype_'))? true : false);
});
?>
 </select>
 <input type="text" name="topspeed" value="<?= post_ ('topspeed')?>" placeholder="<?= _abc ('topspeed')?>" />
</span>