<div class="w3-container">
	<a href="<?= SiteURL.'?home'?>">
		<span class="w3-xxlarge">Hrach</span>
		<sup style="font-family:'Arial';color:red;">Framework</sup>
	</a>
</div>
<div class="w3-bar w3-hide-large w3-hide-medium" id="mainmenu">
	<div onclick="w3.toggleClass('#links', 'w3-hide-small');" class="w3-bar-item w3-large w3-amber">Menu</div>
</div>
<div class="w3-container w3-padding w3-animate-left w3-hide-small" id="links">
	<a href="<?= SiteURL.'?home/'.ModelSettings ?>">
		<span><?= _abc(ModelSettings)?></span>
	</a>
	<a href="<?= SiteURL.'?home/'.ValidationCode ?>">
		<span><?= _abc(ValidationCode)?></span>
	</a>
	<a href="<?= SiteURL.'?home/'.StrongPass ?>">
		<span><?= _abc(StrongPass)?></span>
	</a>
</div>