<div class="w3-container w3-bottom w3-teal">
	<div class="w3-animate-zoom w3-margin" style="display:none;" id="mainmenu">
		<a class="w3-btn" href="<?= SiteURL ?>?home/welcome">CCenter</a>
		<a class="w3-btn" href="<?= SiteURL ?>?home/strongpass"><?= _abc('strongpass') ?></a>
		<a class="w3-btn" href="<?= SiteURL ?>?home/dbtomodel"><?= _abc('dbtomodel') ?></a>
	</div>
	<button onclick="w3.toggleShow('#mainmenu');" class="w3-button w3-large w3-amber">Menu</button>
</div>