<div class="w3-col l12 m12 s12">
	<div class="w3-row-padding">
		<form class="w3-col l3 m4 s12" id="codeform">
			<label for="varname"><?= _abc('varname')?></label>
			<input name="varname" type="text" class="w3-input w3-border w3-margin-bottom" id="varname" value="" />
			<select name="form_filters" id="form_filters" class="w3-select w3-border w3-margin-bottom">
				<option value=""><?= _abc('vartype')?></option>
<?php
foreach (filter_list() as $i => $flt) {
	if ($flt) {
		echo "<option value='$i'>".$flt.'</option>';
	}
}
?>
			</select>
			<select name="form_regexp" class="w3-select w3-border" id="form_regexp">
				<option value=""><?= _abc('regexp')?></option>
<?php
lib_load('validation');

$rc = new ReflectionClass('ValidationBase');
foreach ($rc->getConstants() as $constName => $regexp) {
	if ($regexp) {
		echo '<option value="'.strtolower($constName).'">'.$constName.'</option>';
	}
}

unset($rc, $ind);
?>
			</select>
			<div class="w3-row">
				<div class="w3-half">
					<label for="minlength"><?= _abc('minlength')?></label>
					<input name="minlength" type="text" class="w3-input w3-border" id="minlength" value="" size="4" />
				</div>
				<div class="w3-half">
					<label for="maxlength"><?= _abc('maxlength')?></label>
					<input name="maxlength" type="text" class="w3-input w3-border" id="maxlength" value="" size="4" />
				</div>
				<div class="w3-col">
					<input name="enum" type="checkbox" class="w3-check w3-margin-bottom" id="enum" value="1" />&nbsp;<label for="enum"><strong><?= _abc('enum')?></strong></label><br>
					<label for="maxlength"><?= _abc('mysqlquery')?></label>
					<input name="mysqlquery" type="text" class="w3-input w3-border" id="mysqlquery" value="" size="4" />
				</div>
			</div>
			<input name="clientinputs" type="submit" id="generate_btn" class="w3-btn w3-orange" value="<?= _abc('generate')?>" />
		</form>
		<div class="w3-col l7 m8 s12">
			<pre class="w3-panel w3-margin w3-small" id="generated_code"></pre>
			<div id="clrgeneddata" class="w3-panel w3-green" disabled="disabled"><?= _abc('clgendata')?></div>
		</div>
	</div>
	<script type="text/javascript">
	var PHPBridge = {};
	PHPBridge.error_varname = "<?= _abc('error_varname')?>";
	PHPBridge.error_filter_or_regexp = "<?= _abc('error_filter_or_regexp')?>";
	PHPBridge.error_not_numeric = "<?= _abc('error_not_numeric')?>";
	PHPBridge.ajax_url = "<?= SiteURL.'?home/'.ValidationCode?>";
	</script>
	<script type="text/javascript" src="client/js/validationcode.js"></script>
</div>
