<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<?php __('cpage')->meta(); ?>
		<title><?= __('page')->getTitle()?></title>
		<link rel="stylesheet" href="../shared/w3/w3.css" type="text/css" />
		<link rel="stylesheet" href="client/css/common.css" type="text/css" />
		<?= HTMLHelpers::JSScript('../shared/jquery/jquery-3.3.1.min.js') ?>
		<?= HTMLHelpers::JSScript('../shared/w3/w3.js') ?>
		<?= HTMLHelpers::JSScript('../shared/hrachefront/HracheJS.js') ?>
		<?php __('cpage')->topres(); ?>
		<style type="text/css">
		<?php __('cpage')->csscode(); ?>
		</style>
	</head>
	<body class="w3-white">
		<?php __('page')->snippet->insert('header'); ?>
		<div class="w3-row">
		<?php __('cpage')->content(); ?>
		</div>
		<?php __('cpage')->bottomres(); ?>
		<script type="text/javascript" src="client/js/common.js"></script>
		<script type="text/javascript">
		<?php __('cpage')->jscode(); ?>
		</script>
	</body>
</html>
