<h2><?= _abc('accountinfo') ?></h2>
<span class="account-info">
<?php
if (!_db('account')) {
	return false;
}

function infoItem(string $title, string $text): void {
	printf('<span><span>%s</span>%s</span>', $title, $text);
}

$account = __('account');
$titles = [
	AccountModel::name => _abc('name'),
	AccountModel::surname => _abc('surname'),
	AccountModel::birthday => _abc('birthday'),
	AccountModel::gender => _abc('gender'),
	AccountModel::phonecodeid => _abc('phonecode'),
	AccountModel::phonenumber => _abc('phonenumber'),
	AccountModel::email => _abc('email'),
	AccountModel::signupdate => _abc('signupdate'),
	AccountModel::lastvisit => _abc('lastvisit'),
];
foreach ($titles as $i => $val) {
	$iAccount = $account->$i;
	if (!$account->$i) {
		continue;
	} elseif ($account->$i === 'm') {
		$iAccount = _abc('man');
	} elseif ($account->$i === 'w') {
		$iAccount = _abc('woman');
	} elseif ($i == AccountModel::phonecodeid) {
		$account->$i = PostalInfoCustom(intval($account->$i))->item(0);
		$country = AcsCountryinfoTblModel::nicename;
		$phonecode = AcsCountryinfoTblModel::phonecode;
		$iAccount = $account->$i->$country . ' - ' . $account->$i->$phonecode;
		unset($country, $phonecode);
	}
	infoItem(ucfirst($val), $iAccount);
}
$personal_add = json_decode($account->personal_additional);
foreach ($personal_add as $title => $info) {
	if (!boolval($info)) {
		continue;
	}
	infoItem(_abc($title), $info);
}
?>
</span>