<?php
__('page')->setSnippetsPath(Snippets.'newadv'.ds);

__('language')->append('currencies');
?>
<h2><?= _abc('requiredinfo') ?></h2>
<form class="form-theme" name="newadvform" id="newadvform" action="<?= SiteURL . '?advertisements/add' ?>" method="post" enctype="multipart/form-data">
	<?php
	__('page')->snippet->insert('adv_required_info');
	__('page')->snippet->insert('vehicleimgs');
	__('page')->snippet->insert('vehicleaddinfo1');
	__('page')->snippet->insert('vehicleaddinfo2');
	__('page')->snippet->insert('adv_description');
	?>
	<span class="col-1-1">
		<input type="submit" value="<?= _abc('save') ?>" />
	</span>
</form>
<?php __('page')->setSnippetsPath(Snippets); ?>