<span class="col-1-1 menu3">
 <?php
 $menuLinks = [
     'support' => ["text" => _abc("support")],
     'termsofuse' => ["text" => _abc("termsofuse")],
     'privacy' => ["text" => _abc("privacy")]];
 createmenu($menuLinks, [
     'active' => 'menu-active-link',
     'page' => CurrentPage,
     'url' => SiteURL . '?',
     'vertical' => true,]);
 ?>
</span>
<span class="col-1-1" dir="rtl">&nbsp;Author: <a href="<?= dirname(SiteURL) ?>"><i>Max Pyger</i></a></span>