<form class="w3-content" action="<?= SiteURL?>?account/signup" id="signupform" name="signupform" method="POST" accept-charset="UTF-8">
	<h1 class="w3-padding"><?= _abc('createaccount') ?></h1>
	<div class="w3-row-padding">
		<div class="w3-half">
			<label for="<?= Accounts::email ?>"><?= _abc('email') ?></label>
			<input type="text" class="w3-input w3-border" name="<?= Accounts::email ?>" id="<?= Accounts::email ?>" value="<?= post_('signupemail') ?>" />
			<label for="<?= Accounts::email ?>c"><?= _abc('confirmemail') ?></label>
			<input type="text" class="w3-input w3-border" name="<?= Accounts::email ?>c" id="<?= Accounts::email ?>c" value="<?= post_('signupemailc') ?>" />
			<label for="<?= Accounts::password ?>"><?= _abc('password') ?></label>
			<input type="password" class="w3-input w3-border" name="<?= Accounts::password ?>" id="<?= Accounts::password ?>" />
			<label for="<?= Accounts::password ?>c"><?= _abc('confirmpassword') ?></label>
			<input type="password" class="w3-input w3-border" name="<?= Accounts::password ?>c" id="<?= Accounts::password ?>c" />
			<div class="w3-cell-row w3-margin-top">
				<div class="w3-cell w3-cell-top">
					<label for="<?= Accounts::country_id ?>"><?= _abc('country') ?></label>
				</div>
				<div class="w3-cell">
					<select class="w3-select" name="<?= Accounts::country_id ?>" id="country_id">
						<option value=""></option>
					</select>
				</div>
			</div>
			<label for="<?= Accounts::phonenumber ?>"><?= _abc('phonenumber') ?></label>
			<input type="text" name="<?= Accounts::phonenumber ?>" class="w3-input w3-border" id="<?= Accounts::phonenumber ?>" value="<?= post_('phonenumber') ?>" />
		</div>
		<div class="w3-half">
			<label for="<?= Accounts::name ?>"><?= _abc('firstname') ?></label>
			<input type="text" class="w3-input w3-border" name="<?= Accounts::name ?>" id="<?= Accounts::name ?>" value="<?= post_('firstname') ?>" />
			<label for="<?= Accounts::surname ?>"><?= _abc('lastname') ?></label>
			<input type="text" class="w3-input w3-border" name="<?= Accounts::surname ?>" id="<?= Accounts::surname ?>" value="<?= post_('lastname') ?>" />
			<div class="w3-cell-row w3-margin-top">
				<div class="w3-cell w3-cell-top w3-text-right">
					<label for="<?= Accounts::gender ?>"><?= _abc('gender') ?></label>
				</div>
				<div class="w3-cell">
					<select id="<?= Accounts::gender ?>" name="<?= Accounts::gender ?>" class="w3-select w3-margin-bottom">
						<option value=""></option>
						<option value="m" <?= (post_('gender') === 'm')? 'checked' : '' ?>><?= _abc("man") ?></option>
						<option value="w" <?= (post_('gender') === 'w')? 'checked' : '' ?>><?= _abc("woman") ?></option>
					</select>
				</div>
			</div>
			<div class="w3-cell-row">
				<div class="w3-cell">
					<label for="byear"><?= _abc('year') ?></label>
				</div>
				<div class="w3-cell w3-cell-top">
					<select id="byear" class="w3-select w3-margin-bottom">
						<option value=""></option>
					</select>
				</div>
			</div>
			<div class="w3-cell-row">
				<div class="w3-cell">
					<label for="bmonth"><?= _abc('month') ?></label>
				</div>
				<div class="w3-cell w3-cell-top">
					<select id="bmonth" class="w3-select w3-margin-bottom">
						<option value=""></option>
						<?php html_dropdown_items(_abc('months'), !is_numeric(post_('birthmonth'))? -1 : post_('birthmonth')); ?>
					</select>
				</div>
			</div>
			<div class="w3-cell-row">
				<div class="w3-cell">
					<label for=""><?= _abc('day') ?></label>
				</div>
				<div class="w3-cell w3-cell-top">
					<select id="bday" class="w3-select w3-margin-bottom">
						<option value=""></option>
						<?= DOMRangeOptions(1, 31, post_('birthday'), 1) ?>
					</select>
				</div>
			</div>
			<input type="hidden" id="<?= Accounts::birthday ?>" name="<?= Accounts::birthday ?>" value="" />
			<input type="hidden" name="dateformat" id="dateformat" value="dd-mm-yyyy" />
		</div>
	</div>
	<div class="w3-row w3-padding">
		<div class="w3-col">
			<div style="word-wrap:break-word;">
				<input type="checkbox" class="w3-check" name="signin" id="signinsftersignup" value="1" checked="checked" />
				<label for="signinsftersignup"><?= _abc('signinaftersignup') ?></label>
			</div>
		</div>
	</div>
</form>
<div class="w3-content w3-center w3-padding">
	<button class="w3-btn w3-lime" id="createaccount"><?= _abc('createaccount') ?></button>
</div><!-- Signup form -->