<?php
$menulinks = [
	"hy-AM" => [
		"link" => "&lang=hy-am",
		"flagcss" => "flag-armenia"
	],
	"ru-RU" => [
		"link" => "&lang=ru-ru",
		"flagcss" => "flag-russia"
	],
	"en-UK" => [
		"link" => "&lang=en-uk",
		"flagcss" => "flag-britain"
	]
];
?>
<span class="col-1" dir="rtl">
<?php
foreach ($menulinks as $key => $val) {
	$val = (object) $val;
	printf('<a href="%s" class="%s %s">%s</a>', SiteURL.'?'.CurrentPage.$val->link, $val->flagcss, ($key == Lang) ? 'menu-active-link' : '', '');
}
?>
</span>