<div class="w3-container w3-padding">
	<a href="<?= SiteURL.'?'.CurrentPage."&lang=en-uk" ?>" class="w3-border">
		<img class="w3-image" src="client/images/flags/gb.jpg" />
	</a>
	<a href="<?= SiteURL.'?'.CurrentPage."&lang=hy-am" ?>">
		<img class="w3-image" src="client/images/flags/arm.jpg" />
	</a>
	<a href="<?= SiteURL.'?'.CurrentPage."&lang=ru-ru" ?>">
		<img class="w3-image" src="client/images/flags/ru.jpg" />
	</a>
</div>